### ISSUE TITLE
Remove explicit "children" passing

### ISSUE THREAD

**Issue by RasmusKlett** [Astrocoders/reason-epitath#1]
In the "Next steps" section of the Readme you mention changing the usage to 
```reason
let%Epitath passwordState = <State initialState="" />;
```
which removes the explicit handling of children. Do you have a working method of doing this?
The closest I've been able to get is:
```reason
module Epitath = {
  let let_ = (children, render) => ReasonReact.element(children(render));
}

//Usage
let%Epitath passwordState = State.make(~initialState="");
```

This is still an improvement to me, but I like your suggestion better because it is more obvious that we are creating a React component. I just don't see how to define `let_` to allow it.

**Comment by RasmusKlett** [comment]
Huh, it seems the same idea has [already been implemented](https://github.com/Astrocoders/bs-epitath/pull/6), just not documented. Guess this should be closed.

**Comment by fakenickels** [comment]
Hey there! Sorry to not have answered earlier, but yea, it was released as a `Hook`
